# -*- coding: utf-8 -*-
"""0072_Muhammad_Raka_Mushaddaq_UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4NDbzsuTTeY32dIDqIGkB6XNVyEqxEk

1. Buatlah program python untuk mendeteksi bilangan ganjil atau genap pada NIM masing-masing mahasiswa!
"""

angka = print(input("Masukkan NIM anda: "))
if angka % 2 == 0:
    print(angka, "NIM anda termasuk bilangan genap")
else:
    print(angka, "NIM anda termasuk bilangan ganjil")

"""2. Buatlah program python dengan percobaan berulang yang meminta pengguna untuk memasukkan username dan password yang telah ditentukan!"""

username = (input("Masukkan username: "))
password = (input("Masukkan password: "))

if username == "admin" and password == 12345:
  print("Login berhasil!")
  break
else:
  print("username atau password salah")


username = (input("\nMasukkan username: "))
password = (input("Masukkan password: "))


if username == "admin" and password == 12345:
  print("Login berhasil!")
  break
else:
  print("username atau password salah")


username = (input("\nMasukkan username: "))
password = (input("Masukkan password: "))


if username == "admin" and password == 12345:
  print("Login berhasil!")
else:
  print("Akun terkunci!")

